"""update userpayment table

Revision ID: 2882d1f66824
Revises: bccb0f4e3132
Create Date: 2024-08-14 08:02:06.447550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2882d1f66824'
down_revision = 'bccb0f4e3132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receipt_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payments', schema=None) as batch_op:
        batch_op.drop_column('receipt_url')
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
