"""Add seller_id to UserPayment

Revision ID: a4a1539e59ad
Revises: 2882d1f66824
Create Date: 2024-08-14 09:12:41.498898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a1539e59ad'
down_revision = '2882d1f66824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_user_payments_seller_id',  # Name of the constraint
            'users',                       # Referenced table
            ['seller_id'],                 # Column in the current table
            ['id']                         # Column in the referenced table
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_payments_seller_id', type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
